// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloService.proto

package com.denglitong.grpc_demo.gencode.helloworld;

public final class HelloServiceOuterClass {
  private HelloServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_denglitong_grpc_demo_gencode_helloworld_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_denglitong_grpc_demo_gencode_helloworld_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_denglitong_grpc_demo_gencode_helloworld_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_denglitong_grpc_demo_gencode_helloworld_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022HelloService.proto\022+com.denglitong.grp" +
      "c_demo.gencode.helloworld\"B\n\014HelloReques" +
      "t\022\021\n\tfirstName\030\001 \001(\t\022\020\n\010lastName\030\002 \001(\t\022\r" +
      "\n\005email\030\003 \001(\t\"!\n\rHelloResponse\022\020\n\010greeti" +
      "ng\030\001 \001(\t2\216\001\n\014HelloService\022~\n\005hello\0229.com" +
      ".denglitong.grpc_demo.gencode.helloworld" +
      ".HelloRequest\032:.com.denglitong.grpc_demo" +
      ".gencode.helloworld.HelloResponseB\002P\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_denglitong_grpc_demo_gencode_helloworld_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_denglitong_grpc_demo_gencode_helloworld_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_denglitong_grpc_demo_gencode_helloworld_HelloRequest_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Email", });
    internal_static_com_denglitong_grpc_demo_gencode_helloworld_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_denglitong_grpc_demo_gencode_helloworld_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_denglitong_grpc_demo_gencode_helloworld_HelloResponse_descriptor,
        new java.lang.String[] { "Greeting", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
